export const GET_USERS = 'GET_USERS';
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const SET_SIGNEDINUSER = 'SET_SIGNEDINUSER';
export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_QUESTION_TO_USER = 'ADD_QUESTION_TO_USER';
export const SAVE_QUESTION_ANSWER = 'SAVE_QUESTION_ANSWER';
export const SAVE_ANSWER_TO_USER = 'SAVE_ANSWER_TO_USER';
